spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/ECom_Payment
    username: root
    password: Pavan@2010

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update