spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ECom_User
    username: root
    password: Pavan@2010

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: kanna728680@gmail.com
#    password: iWcMuPe4d!
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
