spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ECom_Order
    username: root
    password: Pavan@2010

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  zipkin:
   base-url: http://127.0.0.1:9411/




management:
  tracing:
    sampling:
      probability: 1.0


